### ISSUE TITLE
Collision of shortcut

### ISSUE THREAD

**Issue by cnaa97** [mohnish/rearrange-tabs#29] opened 2018-09-13 05:22 UTC
In Chrome 69 (Mac), default keyboard shortcut crashes.

Basic shortcut is `Ctrl + Shift + Left/Right`. 

But Chrome 69, `Alt + Shift + Left/Right` is also works.

Using `Art` crashes system shortcut of mac.

**Comment by mohnish** [comment] 2018-09-21 06:42
Hello @cnaa97, thanks for taking time to open this issue. This is currently a known issue. There's another issue opened regarding the same problem here: https://github.com/mohnish/rearrange-tabs/issues/27

I am looking into the issue and so far I haven't really found what's causing the problem. I'll definitely push a fix out as soon as I find the root cause. Thanks for using the extension and sorry about the annoying bug.

**Comment by mohnish** [comment] 2018-10-25 00:39
Closing this in favor of this https://github.com/mohnish/rearrange-tabs/issues/27, just so we have all the discussion at one place.

**Closed by mohnish** 2018-10-25 00:39 UTC
Labels: duplicate
