### ISSUE TITLE
Mac default shortcuts are problematic in address bar

### ISSUE THREAD

**Issue by garyking** [mohnish/rearrange-tabs#34] opened 2019-08-25 04:07 UTC
When the cursor is focused in the address bar on a Mac, and I hit Opt-Shift-Left/Right arrow to select a word in the address bar (this is the universal key combo on Mac), then it instead moves the tab left and right, even when I'm using the default shortcuts, which are Ctrl-Shift-Left/Right.

**Comment by nunoh** [comment] 2019-10-02 13:13
This is happening for me too with pinned tabs. For unpinned tabs it works as expected.

**Comment by joaocunha** [comment] 2020-03-14 21:22
This made it work: https://github.com/mohnish/rearrange-tabs/issues/27#issuecomment-433097302

**Comment by mohnish** [comment] 2020-03-16 17:38
@joaocunha Hi João! This is not really the ideal solution. There is an issue with this that I've pointed out here: https://github.com/mohnish/rearrange-tabs/issues/27#issuecomment-433214090

If you want a better alternative that works, try this: https://github.com/mohnish/rearrange-tabs/issues/27#issuecomment-454626741

**Comment by mohnish** [comment] 2020-03-16 17:39
I am closing this as a duplicate of https://github.com/mohnish/rearrange-tabs/issues/27

**Closed by mohnish** 2020-03-16 17:39 UTC
