### ISSUE TITLE
option+shift+left/right moves tabs when search bar is focused

### ISSUE THREAD

**Issue by MiLeung** [mohnish/rearrange-tabs#33] opened 2019-04-11 03:21 UTC
This makes highlighting the next word with shift+left/right arrows impossibru

**Comment by mohnish** [comment] 2019-04-11 18:07
@MiLeung thanks for taking time to open this issue. this is a known issue as of Chrome 69, unfortunately.

the current work around is to configure the shortcuts to use `CMD+Ctrl+<arrows>`

duplicate of https://github.com/mohnish/rearrange-tabs/issues/27

**Closed by mohnish** 2019-04-11 18:07 UTC
